/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mylittleshutin;

import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 * This is the main game screen.
 * It retrieves the selected character from the load menu
 * or the created character from New Game on the main menu
 * 
 * @author Nigel
 */
public class GameInstance extends javax.swing.JFrame {
	private ShutIn character;
	private DatabaseOps saveOps;
	
	public GameInstance() {
		initComponents();
	}
	
	public void getCharacter(ShutIn si) { //Gets ShutIn object from other classes.
		character = si;
	}
	
	public void updateSprites() { //Updates the character sprites (migrated from GameTime.java)
		double scales = character.getBodyweight();
		if(scales >= 300.0) {
			avatarArea.setText(Sprites.giganticSprite);
		}else if(scales >= 200.0) {
			avatarArea.setText(Sprites.hugeSprite);
		}else if(scales >= 100.0) {
			avatarArea.setText(Sprites.fatSprite);
		}else {
			avatarArea.setText(Sprites.skinnySprite);
		}
	}
	
	public void updateUI() { //Updates stats shown on the UI Screen
		hungerStat.setText(String.valueOf(character.getHunger()));
		boreStat.setText(String.valueOf(character.getBoredom()));
		healthStat.setText(String.valueOf(character.getHealth()));		
		fundStat.setText("$" + String.valueOf(character.getFunds()));
		updateSprites();
		nextDayBtn.setText("End Day " + character.getDaysPassed());
	}
	
	public void runGame() { //Progresses the game time and updates UI
		GameTime game = new GameTime(character);
		character.updateStatus();
		character.addDay();
		updateUI();
		if(character.checkAlive() == true) {
			game.runEvent();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        updateArea = new javax.swing.JScrollPane();
        mainTextArea = new javax.swing.JTextArea();
        profileBtn = new javax.swing.JButton();
        storeVisit1 = new javax.swing.JButton();
        nextDayBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mainMenuBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        commandInput = new javax.swing.JTextArea();
        enterCommandBtn = new javax.swing.JButton();
        hungerStat = new javax.swing.JLabel();
        boreStat = new javax.swing.JLabel();
        healthStat = new javax.swing.JLabel();
        fundStat = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        avatarArea = new javax.swing.JTextPane();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setText("Hunger");

        jLabel3.setText("Hunger");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainTextArea.setColumns(20);
        mainTextArea.setLineWrap(true);
        mainTextArea.setRows(5);
        updateArea.setViewportView(mainTextArea);

        jScrollPane1.setViewportView(updateArea);

        profileBtn.setText("View Profile");
        profileBtn.setEnabled(false);
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        storeVisit1.setText("Visit Store");
        storeVisit1.setEnabled(false);
        storeVisit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeVisit1ActionPerformed(evt);
            }
        });

        nextDayBtn.setBackground(new java.awt.Color(51, 153, 0));
        nextDayBtn.setText("End Day");
        nextDayBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextDayBtnMouseClicked(evt);
            }
        });

        jLabel4.setText("Funds");

        jLabel5.setText("Boredom");

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("CharNameHere");

        jLabel6.setText("Hunger");

        jLabel7.setText("Health");

        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMenuBtnMouseClicked(evt);
            }
        });

        commandInput.setColumns(20);
        commandInput.setRows(5);
        commandInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                commandInputKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(commandInput);

        enterCommandBtn.setText("Enter");
        enterCommandBtn.setEnabled(false);

        hungerStat.setText("hun");

        boreStat.setText("bore");

        healthStat.setText("Hel");

        fundStat.setText("mone");

        avatarArea.setEditable(false);
        avatarArea.setFont(new java.awt.Font("Dialog", 1, 6)); // NOI18N
        avatarArea.setText("           \n         /  \\\\     \n        -------    \n       @        @     \n       @        @     \n       @@ @@     \n         @       \n      @@   @@    \n     @ @   @ @   \n     @ @-1-@ @   \n       @   @     \n       @@@@@     \n       @   @     \n       @   @     \n      @@   @@@   ");
        avatarArea.setToolTipText("");
        jScrollPane3.setViewportView(avatarArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(profileBtn)
                        .addGap(18, 18, 18)
                        .addComponent(storeVisit1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterCommandBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(nextDayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boreStat)
                            .addComponent(hungerStat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(healthStat))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fundStat)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(mainMenuBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(hungerStat)
                            .addComponent(healthStat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(boreStat)
                            .addComponent(fundStat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profileBtn)
                            .addComponent(storeVisit1)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nextDayBtn)
                        .addComponent(enterCommandBtn))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        nextDayBtn.getAccessibleContext().setAccessibleName("f");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuBtnMouseClicked
		int yesNoDialog = JOptionPane.YES_NO_OPTION; //Shows popup confirming return to mainMenu
		yesNoDialog = JOptionPane.showConfirmDialog(null, 
				"Would you like to return to the Main Menu?", "Warning", yesNoDialog);
		
		if(yesNoDialog == JOptionPane.YES_OPTION) {
			new StartScreen().setVisible(true);
			this.setVisible(false);
		}
    }//GEN-LAST:event_mainMenuBtnMouseClicked

    private void nextDayBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextDayBtnMouseClicked
		saveOps.saveRecord(character);
		runGame();
    }//GEN-LAST:event_nextDayBtnMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        saveOps = new DatabaseOps();
		saveOps.estabConnection();
		nameLabel.setText(character.getShutInName());
		updateUI();
		mainTextArea.append("Press 'End Day' to Continue'\n");
		redirectSystemStreams();
    }//GEN-LAST:event_formWindowOpened

    private void storeVisit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeVisit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeVisit1ActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileBtnActionPerformed

    private void commandInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commandInputKeyPressed

    }//GEN-LAST:event_commandInputKeyPressed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GameInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GameInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GameInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GameInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GameInstance().setVisible(true);
			}
		});
	}
	
	
	private void updateTextArea(final String text) {
		SwingUtilities.invokeLater(new Runnable() {
		  public void run() {
			mainTextArea.append(text);
		  }
		});
	}

    private void redirectSystemStreams() { //Reproduces Console in GUI
		OutputStream out = new OutputStream() {
			@Override
			public void write(int b) throws IOException {
			  updateTextArea(String.valueOf((char) b));
			}

			@Override
			public void write(byte[] b, int off, int len) throws IOException {
			  updateTextArea(new String(b, off, len));
			}

			@Override
			public void write(byte[] b) throws IOException {
			  write(b, 0, b.length);
			}
		};

		System.setOut(new PrintStream(out, true));
		System.setErr(new PrintStream(out, true));
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane avatarArea;
    private javax.swing.JLabel boreStat;
    private javax.swing.JTextArea commandInput;
    private javax.swing.JButton enterCommandBtn;
    private javax.swing.JLabel fundStat;
    private javax.swing.JLabel healthStat;
    private javax.swing.JLabel hungerStat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JTextArea mainTextArea;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton nextDayBtn;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton storeVisit1;
    private javax.swing.JScrollPane updateArea;
    // End of variables declaration//GEN-END:variables
}
