/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mylittleshutin;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * This class handles the Main Menu that appears when the
 * program is first launched. It displays the available saves
 * in the main pane. 
 * 
 * @author Nigel
 */
public class StartScreen extends javax.swing.JFrame {
	DatabaseOps dataOps;
	ShutIn selectedSave;
	/**
	 * Creates new form StartScreen
	 */
	public StartScreen() {
		initComponents();
	}
	
	private boolean populateTable() { //Populates Save table at StartScreen
		try {
			dataOps = new DatabaseOps();
			dataOps.estabConnection();
			ArrayList recordList = dataOps.getRecord("ß");
			DefaultTableModel model = (DefaultTableModel) saveTable.getModel();
			for(Object si : recordList) {
				ShutIn record = (ShutIn)si;
				model.addRow(new Object[] {record.getShutInName(), record.getTextBodyweight(), record.getDaysPassed()});
			}
			return true;
		} catch(Exception err) {
			System.err.println(err);
			return false;
		}
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        newGameBtn = new javax.swing.JButton();
        loadGameBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        saveTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jButton2.setText("New Game");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        newGameBtn.setText("New Game");
        newGameBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameBtnMouseClicked(evt);
            }
        });

        loadGameBtn.setText("Load Selected Game");
        loadGameBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadGameBtnMouseClicked(evt);
            }
        });

        quitBtn.setText("Quit");
        quitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitBtnMouseClicked(evt);
            }
        });

        jLabel1.setText("Available Saved Games:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("My Little Shut-In");

        saveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Weight", "Days Passed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        saveTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(saveTable);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel3.setText("For Help, see the UserGuide.txt and Readme.txt in the Game's folder");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(loadGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(126, 126, 126))))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newGameBtn)
                    .addComponent(quitBtn)
                    .addComponent(loadGameBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitBtnMouseClicked
        dataOps.closeConnection();
		System.exit(0);
    }//GEN-LAST:event_quitBtnMouseClicked

    private void newGameBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameBtnMouseClicked
		dataOps.closeConnection();
		new NewGameForm().setVisible(true);
		this.setVisible(false);
    }//GEN-LAST:event_newGameBtnMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
		try {
			dataOps = new DatabaseOps();
			dataOps.estabConnection();
			dataOps.createDatabase();
			dataOps.insertSamples();
		} catch (Exception err) {
			System.err.println("Cannot create Database: " + err);
		}
		
		if(populateTable() == false) {
			dataOps.insertSamples();
			populateTable();
		}
    }//GEN-LAST:event_formWindowOpened

    private void loadGameBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadGameBtnMouseClicked
        //selectedSave = selectedSave.listToCharacter(dataOps.getRecord("TESTTESTTEST"));
		if(selectedSave == null) {
			JOptionPane.showMessageDialog(this, "No Save Selected!");
		} else {
			GameInstance GI = new GameInstance();
			GI.getCharacter(selectedSave);
			dataOps.closeConnection();
			GI.setVisible(true);
			this.setVisible(false);
		}

    }//GEN-LAST:event_loadGameBtnMouseClicked

    private void saveTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTableMouseClicked
		int i = saveTable.getSelectedRow();	//Gets name from Selected Row, searches for record.
		String selectedName = (String)saveTable.getValueAt(i, 0);
		System.out.println("SAVED NAME: " + selectedName);
		selectedSave = selectedSave.listToCharacter(dataOps.getRecord(selectedName));
		System.out.println(selectedSave);
    }//GEN-LAST:event_saveTableMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StartScreen().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadGameBtn;
    private javax.swing.JButton newGameBtn;
    private javax.swing.JButton quitBtn;
    private javax.swing.JTable saveTable;
    // End of variables declaration//GEN-END:variables
}
